import React from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import Header from "../components2/Header2";
import "../styles/credit-report.css";

const CreditReport = () => {
  const handlePrint = () => {
    window.print();
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Title and header
    doc.setFontSize(20);
    doc.setTextColor(14, 89, 74); // Primary color
    doc.text("Bokamoso Credit Bureau - Credit Report", 20, 20);

    // Customer info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0); // Black
    doc.text("Customer: Jane Doe (ID: 1536457)", 20, 30);
    doc.text("Period: 10/10/2023 to 11/08/2023", 20, 40);

    // Add credit summary content to PDF
    doc.setFontSize(14);
    doc.setTextColor(14, 89, 74); // Primary color
    doc.text("Credit Summary", 20, 55);
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(
      "Your Equinox Credit Summary contains information in your credit file that is crucial in determining your credit standing.",
      20,
      65,
      { maxWidth: 170 }
    );

    // Add table data
    const tableColumn = [
      "Account Type",
      "Total",
      "Balance",
      "Credit Limit",
      "Status",
      "Monthly Payment",
      "With Balance"
    ];
    const tableRows = [
      ["Mortgage", "1", "M123,021", "M113,021", "Open, Never Late", "M3,753", "1"],
      ["Credit", "3", "M26,643", "M23,578", "Open, Never Late", "M350", "3"],
      ["Car Loans", "1", "M15,750", "M11,256", "Open, Never Late", "M200", "1"],
      ["Total", "5", "M165,414", "M147,855", "Open, Never Late", "M4,303", "5"]
    ];

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 75,
      theme: "grid",
      headStyles: {
        fillColor: [14, 89, 74], // Primary color
        textColor: [255, 255, 255] // White
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240]
      },
      margin: { top: 80 }
    });

    // Add footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Bokamoso Credit Bureau", 20, doc.internal.pageSize.height - 10);

    // Save the PDF
    doc.save("bokamoso_credit_report.pdf");
  };

  return (
    <div className="report-container">
      <Header />
      <div className="report-content">
        <header className="report-header">
          <h1>Bokamoso Credit Bureau - Credit Report</h1>
          <div className="report-info-grid">
            <div className="info-group">
              <p><strong>From:</strong> 10/10/2023</p>
              <p><strong>Until:</strong> 11/08/2023</p>
            </div>
            <div className="info-group">
              <p><strong>Customer Number:</strong> 1536457</p>
              <p><strong>Customer Name:</strong> Jane Doe</p>
            </div>
            <div className="info-group">
              <p><strong>Phone:</strong> (+266) 5678 1234</p>
              <p><strong>Address:</strong> 256 Maseru West, Lesotho</p>
            </div>
          </div>
          <div className="action-buttons">
            <button className="action-btn download" onClick={downloadPDF}>
              <span className="icon">📄</span> Download PDF
            </button>
            <button className="action-btn print" onClick={handlePrint}>
              <span className="icon">🖨</span> Print Report
            </button>
          </div>
        </header>

        <section className="credit-summary">
          <h2>Credit Summary</h2>
          <p className="description">
            This credit report provided by Bokamoso Credit Bureau outlines your
            financial behavior and borrowing history. Maintaining timely
            payments and diversified credit accounts will improve your financial
            health.
          </p>

          <div className="table-responsive">
            <table className="summary-table">
              <thead>
                <tr>
                  <th>Account Type</th>
                  <th>Total</th>
                  <th>Balance</th>
                  <th>Credit Limit</th>
                  <th>Status</th>
                  <th>Monthly Payment</th>
                  <th>With Balance</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Mortgage</td>
                  <td>1</td>
                  <td>M123,021</td>
                  <td>M113,021</td>
                  <td>Open, Never Late</td>
                  <td>M3,753</td>
                  <td>1</td>
                </tr>
                <tr>
                  <td>Credit Installments</td>
                  <td>3</td>
                  <td>M26,643</td>
                  <td>M23,578</td>
                  <td>Open, Never Late</td>
                  <td>M350</td>
                  <td>3</td>
                </tr>
                <tr>
                  <td>Car Loans</td>
                  <td>1</td>
                  <td>M15,750</td>
                  <td>M11,256</td>
                  <td>Open, Never Late</td>
                  <td>M200</td>
                  <td>1</td>
                </tr>
                <tr className="total-row">
                  <td>Total</td>
                  <td>5</td>
                  <td>M165,414</td>
                  <td>M147,855</td>
                  <td>Open, Never Late</td>
                  <td>M4,303</td>
                  <td>5</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="data-visualization">
          <div className="debt-distribution">
            <h3>Debt Distribution</h3>
            <div className="chart-container">
              <div className="chart-bars">
                <div className="bar-container">
                  <div className="bar mortgage" style={{ height: '60%' }}>
                    <span className="bar-value">M123,021</span>
                  </div>
                  <span className="bar-label">Mortgage</span>
                </div>
                <div className="bar-container">
                  <div className="bar credit" style={{ height: '80%' }}>
                    <span className="bar-value">M26,643</span>
                  </div>
                  <span className="bar-label">Credit</span>
                </div>
                <div className="bar-container">
                  <div className="bar car" style={{ height: '40%' }}>
                    <span className="bar-value">M15,750</span>
                  </div>
                  <span className="bar-label">Car Loans</span>
                </div>
              </div>
            </div>
          </div>

          <div className="account-details">
            <h3>Account Age</h3>
            <div className="detail-item">
              <span className="detail-label">Credit History:</span>
              <span className="detail-value">10 Years, 11 Months</span>
            </div>
            <div className="detail-item">
              <span className="detail-label">Average Account Age:</span>
              <span className="detail-value">7 years, 2 months</span>
            </div>
            <div className="detail-item">
              <span className="detail-label">Oldest Account:</span>
              <span className="detail-value">CAPITAL BANK LS (14/12/2012)</span>
            </div>
            <div className="detail-item">
              <span className="detail-label">Newest Account:</span>
              <span className="detail-value">BELLS FARGO LS (08/05/2019)</span>
            </div>
          </div>
        </section>

        <section className="inquiries-section">
          <h2>Credit Inquiries</h2>
          <p className="section-description">
            Numerous inquiries can affect your credit profile. Always apply for
            credit responsibly.
          </p>
          <div className="inquiry-list">
            <div className="inquiry-item">
              <span className="inquiry-company">ABC Mortgage Services</span>
              <span className="inquiry-date">24/01/2022</span>
            </div>
            <div className="inquiry-item">
              <span className="inquiry-company">Blue Hill Lending Co.</span>
              <span className="inquiry-date">21/05/2023</span>
            </div>
          </div>
        </section>

        <footer className="report-footer">
          <div className="footer-content">
            <div className="footer-info">
              <p>Maseru, Lesotho</p>
              <p>Email: info@bokamoso.co.ls</p>
            </div>
            <div className="footer-info">
              <p>Phone: (+266) 2233 4455</p>
              <p>Website: www.bokamosocredit.co.ls</p>
            </div>
          </div>
          <p className="copyright">© {new Date().getFullYear()} Bokamoso Credit Bureau. All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
};

export default CreditReport;